name: Build and push

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }} @ build-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get safe branch name and PR number
        id: tags
        run: |
          BRANCH_NAME=$(echo "${{ github.head_ref || github.ref_name }}" | sed 's,[/.],_,g')
          if [[ -f "$GITHUB_EVENT_PATH" ]]; then
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=" >> $GITHUB_OUTPUT
          fi
          echo "safe_branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          tags: |-
            ghcr.io/wurly200a/builder-linux:${{ github.sha }}
            ghcr.io/wurly200a/builder-linux:latest
